image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
tasks:
  - init: cargo bootimage
    command: qemu-system-x86_64 -drive format=raw,file=target/x86_64-hello_os/debug/bootimage-hello_os.bin
